### PR TITLE
Remove average posts graph

### PR DESCRIPTION
**Pull request by oilnam**

### CODE REVIEW

**Comment by LATaylor-guardian** [comment]
It also needs to be removed from here:
https://github.com/guardian/bard/blob/master/app/com/gu/bard/settings/MetricSettings.scala#L17

**Comment by LATaylor-guardian** [comment]
And here:
https://github.com/guardian/bard/blob/master/app/com/gu/bard/settings/PageInsightsPageSettings.scala#L8

**Comment by oilnam** [comment]
Whoops - thanks

**Comment by LATaylor-guardian** [comment]
👍  (this project has continuous deployment enabled)

**Pull request merged**
